### PR TITLE
ported fix from bndg C10485

### PR DESCRIPTION
**Pull request by Sheap**
Can anybody think of any reason this would fail? The fix is live on bndg_prod without any known issues.

### CODE REVIEW

**Comment by Sheap** [comment]
And, being live on bndg_prod - is currently a difference that must be resolved before bndg can be switched over to using cdn.

**Comment by stephenfrancis** [comment]
Reviewed

**Comment by Sheap** [comment]
Can the passing of QA (and significant time in the wild) of this change on bndg be taken as a QA process on the feature itself? Or does the case need a specific QA on cdn?

**Comment by stephenfrancis** [comment]
I think this is fine.

**Pull request merged**
